soul:
  package_name: "cn.soulapp.android"
  chat_activity: ".component.startup.main.MainActivity"
  # default_party_id: "FM18633292"
  default_party_id: "FM15321640" 
  default_notice: "U Share I Play\n分享音乐 享受快乐"
  elements:
    message_list: "cn.soulapp.android:id/rvMessage"
    message_content: "cn.soulapp.android:id/tvContent"
    input_box_entry: "cn.soulapp.android:id/tvChat"
    input_box: "cn.soulapp.android:id/etInputView"
    button_send: "cn.soulapp.android:id/btnSend"
    new_message_tip: "cn.soulapp.android:id/tvNewMsgTip"
    floating_entry: "cn.soulapp.android:id/background"
    invite_link: "cn.soulapp.android:id/iv_room_music"
    sender_relation: "cn.soulapp.android:id/ivFlagImg"
    sender_flag: "cn.soulapp.android:id/flagContainerView"
    sender_avatar: "cn.soulapp.android:id/ivAvatar"
    sender_nickname: "cn.soulapp.android:id/tvNickname"
    profile_avatar: "cn.soulapp.android:id/img_head"
    moments_chat: "cn.soulapp.android:id/rl_user_bottom_chat"
    chat_title: "cn.soulapp.android:id/c_ct_chat_title_info"
    manager_invite: "cn.soulapp.android:id/tv_manager_invite"
    confirm_invite: "cn.soulapp.android:id/tv_confirm_invite"
    confirm_dismiss: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_btn' and @text='确认解除']"
    more_menu: "cn.soulapp.android:id/ivChatMore"
    party_hall: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_item' and @text='派对大厅']"
    end_party: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_item' and @text='关闭派对']"
    confirm_end: '//android.widget.TextView[@resource-id="cn.soulapp.android:id/tv_btn" and @text="关闭房间"]'
    more_menu_container: 'cn.soulapp.android:id/moreRootView'
    search_entry: "cn.soulapp.android:id/ivSearch"
    search_box: "cn.soulapp.android:id/commonViewEtSearch"
    search_button: "cn.soulapp.android:id/flRight"
    party_id: "cn.soulapp.android:id/tvFM"
    parties_search: "cn.soulapp.android:id/rvParties"
    grab_mic: "cn.soulapp.android:id/ivUpSeat"
    confirm_mic: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_btn' and @text='确认']"
    toggle_mic: "cn.soulapp.android:id/ivMicButton"
    square_tab: "cn.soulapp.android:id/main_tab_square"
    party_tab: "//android.widget.LinearLayout[@content-desc='派对']"
    no_party_from_home: "cn.soulapp.android:id/tvEmptyContent"
    no_party_from_hall: "cn.soulapp.android:id/tvEmptyDesc"
    party_search_empty: "cn.soulapp.android:id/llEmpty"
    party_search_result: "cn.soulapp.android:id/searchViewPager"
    party_search_entry: "cn.soulapp.android:id/roomCard"
    content_container: "android:id/content"
    reminder_ok: "cn.soulapp.android:id/tvOk"
    party_back: "cn.soulapp.android:id/tv_look"
    expand_seats: "cn.soulapp.android:id/tvHandleUserList" # 收起座位/展开座位
    collapse_seats: '//android.widget.TextView[@resource-id="cn.soulapp.android:id/tvHandleUserList" and @text="收起座位"]'
    party_online: "cn.soulapp.android:id/tvOnline"
    planet_tab: "cn.soulapp.android:id/main_tab_planet" #  星球
    party_hall_entry: '//android.widget.TextView[@resource-id="cn.soulapp.android:id/main_title" and @text="群聊派对"]'
    create_party_entry: "cn.soulapp.android:id/iv_create" #  创建派对
    create_party_button: "cn.soulapp.android:id/createRoomBtn"
    restore_party: "cn.soulapp.android:id/imgRestore"
    confirm_party: "cn.soulapp.android:id/tv_confirm"
    create_party_screen: "cn.soulapp.android:id/rl_room_name"
    claim_reward: "cn.soulapp.android:id/tvCheckReward" # 立即领取/已领取
    room_topic: 'cn.soulapp.android:id/tvStudyRoomTitle'
    edit_topic_entry: 'cn.soulapp.android:id/tvCustomTopic'
    edit_topic_input: 'cn.soulapp.android:id/et_input_message'
    edit_topic_confirm: 'cn.soulapp.android:id/tvConfim'
    little_assistant: 'cn.soulapp.android:id/ivLittleAssistant'
    edit_notice_entry: 'cn.soulapp.android:id/ivEdit'
    customize_notice_button: '//android.view.View[@text="自定义"]'
    customize_notice_disabled: '//android.view.View[@text="修改自定义"]'
    edit_notice_input: '//android.widget.EditText'
    edit_notice_confirm: '//android.view.View[@text="确认提交"]'
    empty_seat: 'cn.soulapp.android:id/leftTvDefaultName'
    up_seat: '//android.widget.TextView[@resource-id="cn.soulapp.android:id/tvOperation" and @text="上座"]'
    edit_announcement_entry: 'cn.soulapp.android:id/ivEdit'
    customize_announcement_button: '//android.view.View[@text="自定义"]'
    edit_announcement_input: '//android.widget.EditText'
    edit_announcement_confirm: '//android.view.View[@text="确认提交"]'
    apply_seat: '//android.widget.TextView[@text="点击入座"]'
    confirm_seat: 'cn.soulapp.android:id/tvOperation'
    chat_room_title: 'cn.soulapp.android:id/tvChatRoomTitle'
    title_edit_entry: 'cn.soulapp.android:id/iv_edit'
    title_edit_input: 'cn.soulapp.android:id/et_content'
    title_edit_confirm: 'cn.soulapp.android:id/tv_confirm'
    go_back: 'cn.soulapp.android:id/iv_back'
    user_count: 'cn.soulapp.android:id/tvUserCount' # 6人
    seat_desk: 'cn.soulapp.android:id/userRoot' #  > left_seat, right_seat
    left_seat: 'cn.soulapp.android:id/leftUserView' # > left_state
    left_state: 'cn.soulapp.android:id/leftClState' # > left_label
    right_seat: 'cn.soulapp.android:id/rightUserView' # > right_state
    right_state: 'cn.soulapp.android:id/rightClState' # > right_label
    left_label: 'cn.soulapp.android:id/leftTvLabelH' #  群主, 管理, 1,3,5,7,9,11
    right_label: 'cn.soulapp.android:id/rightTvLabelH' # 群主, 管理, 2,4,6,8,10,12
    luck_pack: 'cn.soulapp.android:id/tvLbLabelPack' # 福袋 / 2个奖励
    luck_item: 'cn.soulapp.android:id/name' # 初级福袋/中级福袋/高级福袋
    use_pack: 'cn.soulapp.android:id/tvUse' # 使用
    soul_power: 'cn.soulapp.android:id/soulPower' # +12灵魂力
    give_gift: 'cn.soulapp.android:id/btnSend' # 赠送
    gift_tool: 'cn.soulapp.android:id/ivGift'
    follow_list: '//android.widget.LinearLayout[@content-desc="我关注的"]'
    follower_name: 'cn.soulapp.android:id/tvName' # Outlier
    follower_message: 'cn.soulapp.android:id/tvFollowUserContent' # 你关注的Outlier进入房间啦，打个招呼吧～
    greet_follower: 'cn.soulapp.android:id/tvFollowUserNotify' # 打招呼
    send_gift: 'cn.soulapp.android:id/tv_send_four_leaf' # 送礼物
    follow_status: 'cn.soulapp.android:id/tv_follow' # 已关注/关注
    focus_count: 'cn.soulapp.android:id/tvStudyRoomDesc' # 1人专注中
    close_app: 'android:id/aerr_close' # Close app
    seat_off: 'cn.soulapp.android:id/tvSeatDownUp' # 抱下
    souler_name: 'cn.soulapp.android:id/tv_name' # Outlier
    user_name: 'cn.soulapp.android:id/tvUserName' # Joyer
    online_users: 'cn.soulapp.android:id/rvBannedUsers' # 在线用户
    bottom_drawer: 'cn.soulapp.android:id/action_bar_root'
    online_user: 'cn.soulapp.android:id/tvName' # Outlier
    close_notice: '//android.view.View[@text="关闭公告"]'
    search_back: "cn.soulapp.android:id/ivSearchBack"
    close_chat: "cn.soulapp.android:id/tv_btn_close" # 先不聊了
    close_more_menu: "cn.soulapp.android:id/ivBack" # more_menu 的关闭按钮
    activity_back: '//android.widget.Image[@text="此图片未加标签。打开右上角的“更多选项”菜单即可获取图片说明。"]' # 活动页面, 天赋共鸣，群主红包， ...
    close_button: 'cn.soulapp.android:id/ivClose' # 关闭按钮, X 按钮
    h5_back: 'cn.soulapp.android:id/h5_title_back' # 关闭H5页面
    group_back: 'cn.soulapp.android:id/fans_back' # 关闭我的派对群页面
    online_drawer: 'cn.soulapp.android:id/touch_close' # 在线用户抽屉
    share_drawer: 'cn.soulapp.android:id/slide_bar' # 分享至好友抽屉
    input_drawer: 'cn.soulapp.android:id/clSecondContainer' # 输入框抽屉
    room_id: 'cn.soulapp.android:id/tvRoomId'
    room_card: 'cn.soulapp.android:id/roomCard'
    party_hall_back: 'cn.soulapp.android:id/img_back'
    claim_reward_button: '//android.widget.TextView[@resource-id="cn.soulapp.android:id/tvCheckReward" and @text="立即领取"]'
    party_restore_drawer: 'cn.soulapp.android:id/design_bottom_sheet' # 我创建过的派对
    receive_gift: 'cn.soulapp.android:id/ivReceiveGift' # 获得建群礼>立即领取
    create_room_entry: 'cn.soulapp.android:id/btnCreateRoom' # 推荐>创建派对

qq_music:
  package_name: "com.tencent.qqmusic"
  search_activity: ".activity.AppStarterActivity"
  elements:
    search_entry: "com.tencent.qqmusic:id/sub_edit_text"
    search_box: "com.tencent.qqmusic:id/searchItem"
    play_button: "com.tencent.qqmusic:id/kcr"
    next_button: "com.tencent.qqmusic:id/f4"
    player_panel: "com.tencent.qqmusic:id/idm"
    hide_player: "com.tencent.qqmusic:id/na0"
    song_name: "com.tencent.qqmusic:id/mf6"
    singer_name: "com.tencent.qqmusic:id/mhc"
    pause_button: "android:id/action1"
    skip_button: "android:id/action2"
    playing_bar: "com.tencent.qqmusic:id/ha_"
    current_song: "android:id/title"
    current_singer: "android:id/text"
    info_dot: "com.tencent.qqmusic:id/c14"
    details_link: "com.tencent.qqmusic:id/gnw"
    more_in_play_panel: "com.tencent.qqmusic:id/a8r"
    accompaniment_menu: '//android.widget.TextView[@resource-id="com.tencent.qqmusic:id/nr8" and @text="伴唱模式"]'
    accompaniment_switch: "com.tencent.qqmusic:id/or6"
    song_lyrics: "//android.view.View[@resource-id='js_app']/android.view.View/android.view.View[2]"
    full_lyrics: "//android.view.View[@resource-id='js_app']/android.view.View/android.view.View[2]/android.view.View[last()]"
    accompaniment_status: "com.tencent.qqmusic:id/bln"
#    live_lyrics: "com.tencent.qqmusic:id/e5z"
    live_lyrics: "com.tencent.qqmusic:id/lbr"
    accompaniment_tool: "com.tencent.qqmusic:id/ocx"
    lyrics_tool: "com.tencent.qqmusic:id/i2y"
    lyrics_poster: '//android.widget.TextView[@resource-id="com.tencent.qqmusic:id/jmb" and @text="歌词海报"]'
    lyrics_line: "com.tencent.qqmusic:id/h9e"
    lyrics_end: "//android.view.View"
    no_lyrics: "com.tencent.qqmusic:id/ndz"
    clear_search: '//android.widget.ImageView[@content-desc="清空"]'
    current_lyrics: "com.tencent.qqmusic:id/l7_"
    content_container: "android:id/content"
    reminder_ok: "com.tencent.qqmusic:id/icm"
    vocal_tag: "//android.widget.TextView[@resource-id='com.tencent.qqmusic:id/n6i' and @text='原唱']"
    accompaniment_tag: '//android.widget.TextView[@resource-id="com.tencent.qqmusic:id/nj0" and @text="伴唱"]'
    lyrics_box: "com.tencent.qqmusic:id/jah"
    close_poster: "com.tencent.qqmusic:id/b6w"
    accompaniment_bar: "com.tencent.qqmusic:id/or3"
    accompaniment_label: "com.tencent.qqmusic:id/oqz"
    my_nav: '//android.view.ViewGroup[@content-desc="我的"]'
    radar_nav: '//android.view.ViewGroup[@content-desc="雷达"]'
    radar_song: 'com.tencent.qqmusic:id/lxj'
    radar_singer: 'com.tencent.qqmusic:id/lkl'
    fav_entry: 'com.tencent.qqmusic:id/ij0'
    play_fav: 'com.tencent.qqmusic:id/eki'
    fav_song: 'com.tencent.qqmusic:id/lxj'
    fav_singer: 'com.tencent.qqmusic:id/lzn'
    lyrics_tab: '//android.widget.RelativeLayout[@content-desc="歌词 按钮"]'
    playlist_tab: '//android.widget.RelativeLayout[@content-desc="歌单 按钮"]'
    singer_tab: '//android.widget.RelativeLayout[@content-desc="歌手 按钮"]'
    song_tab: '//android.widget.RelativeLayout[@content-desc="歌曲 按钮"]'
    album_tab: '//android.widget.RelativeLayout[@content-desc="专辑 按钮"]'
    album_text: 'com.tencent.qqmusic:id/lg8'
    album_singer: 'com.tencent.qqmusic:id/lg5'
    lyrics_text: 'com.tencent.qqmusic:id/hoi'
    playlist_result: 'com.tencent.qqmusic:id/li6'
    singer_text: 'com.tencent.qqmusic:id/nc8'
    singer_result: 'com.tencent.qqmusic:id/be2'
    play_all: '//android.widget.TextView[@text="全部播放"]'
    play_all_mini: 'com.tencent.qqmusic:id/se'
    singer_container: 'com.tencent.qqmusic:id/hag'
    play_album: 'com.tencent.qqmusic:id/j98'
    play_singer: 'com.tencent.qqmusic:id/em7'
    play_singer_hot: 'com.tencent.qqmusic:id/j0g'
    singer_tabs: '//android.widget.TextView[@text="歌曲"]'
    playlist_item: 'com.tencent.qqmusic:id/ljb'
    go_back: '//android.widget.ImageButton[@content-desc="返回"]'
    studio_version: '//android.widget.RelativeLayout[@content-desc="录音室版 按钮"]'
    playlist_entry: '//android.widget.ImageView[@content-desc="歌曲队列"]'
    playlist_item_container: 'com.tencent.qqmusic:id/jv5'
    playlist_song: 'com.tencent.qqmusic:id/mab'
    playlist_singer: 'com.tencent.qqmusic:id/lxx'
    playlist_current: 'com.tencent.qqmusic:id/eox'
    playlist_header: '//android.widget.TextView[@text="正在播放"]'
    play_mode: 'com.tencent.qqmusic:id/a9j'
    singer_screen: 'com.tencent.qqmusic:id/b_k' #
    playlist_screen: 'com.tencent.qqmusic:id/bay' #
    music_tabs: 'com.tencent.qqmusic:id/be4'

    minimize_screen: '//android.widget.ImageView[@content-desc="返回"]'
    play_all_playlist: '//android.widget.ImageView[@content-desc="全部播放"]'
    play_all_album: '//android.widget.TextView[@text="全部播放"]'
    play_all_singer: '//android.widget.TextView[@text="播放最热歌曲"]'
    playing_record: '//android.view.ViewGroup[@content-desc="专辑封面"]'
    play_next: '//android.widget.ImageView[@content-desc="下一首"]'

    minimize_player: 'com.tencent.qqmusic:id/cp9'

    cancel_drawer: '//android.widget.TextView[@text="取消"]'
commands:
  - prefix: "play"
    response_template: "Playing {song} by {singer} in {album}"
    error_template: "Failed to play music, because {error}"
  - prefix: "skip"
    response_template: "Skipped {song} by {singer}"
    error_template: "Failed to skip song, because {error}"
  - prefix: "next"
    response_template: "Added {song} by {singer} in {album} to playlist"
    error_template: "Failed to add songs to play list, because {error}"
  - prefix: "pause"
    response_template: "{action} {song} by {singer}"
    error_template: "Failed to pause/resume song, because {error}"
  - prefix: "vol"
    response_template: "Adjusted volume to {volume}"
    error_template: "Failed to adjust volume, because {error}"
  - prefix: "acc"
    response_template: "Accompaniment mode {enabled}"
    error_template: "Failed to toggle accompaniment mode, because {error}"
  - prefix: "lyrics"
    response_template: "{lyrics}"
    error_template: "Failed to get lyrics, because {error}"
  - prefix: "ktv"
    response_template: "KTV mode {enabled}"
    error_template: "Failed to toggle KTV mode, because {error}"
  - prefix: "enable"
    response_template: "Enabled: {enabled}"
  - prefix: "help"
    response_template:  |
      Help
      1. play music instantly
        :play song singer 
      2. add music to playlist
        :next song singer
      3. turn on/off accompaniment mode
        :acc 1/0
      4. play next song instantly
        :skip
      5. pause/resume current song
        :pause 1/0
      6. Adjust volume (0~15)
        :vol n
      7. view lyrics of playing song
        :lyrics
      8. view playing song
        :info
      9. play music 
        :playlist music
      10. play singer 
        :singer name
      11. apply/dismiss admin
        :admin 1/0
      12. ktv mode
        :ktv 1/0
      13. play mode
        :mode 0/1/-1

  - prefix: "invite"
    response_template: "Invited by {user} to party {party_id}"
    error_template: "Failed to join party {party_id}, because {error}"
  - prefix: "recovery"
    response_template: "{status}"
    error_template: "Recovery command failed: {error}"
  - prefix: "admin"
    response_template: "{action} {user} as administrator"
    error_template: "Failed to invite {user} as administrator, because {error}"
  - prefix: "info"
    response_template: "Playing {song} by {singer} in {album}, playlist from {player}"
    error_template: "Failed to get playback info, because {error}"
  - prefix: "singer"
    response_template: "Playing {singer}"
    error_template: "Failed to play singer, because {error}"
  - prefix: "playlist"
    response_template: "{playlist}"
    error_template: "Failed to play playlist, because {error}"
  - prefix: "mode"
    response_template: "Change play mode to {mode}"
    error_template: "Failed to change play mode, because {error}"
  - prefix: "topic"
    response_template: "Change topic to {topic}"
    error_template: "Failed to change topic, because {error}"
  - prefix: "notice"
    response_template: "Change notice to {notice}"
    error_template: "Failed to change notice, because {error}"
  - prefix: "album"
    response_template: "Playing album {album}"
    error_template: "Failed to play album, because {error}"
  - prefix: "seat"
    response_template: "{success}"
    error_template: "Failed to apply for seat, because {error}"
  - prefix: "title"
    response_template: "Change title to {title}"
    
    error_template: "Failed to change title, because {error}"
  - prefix: "end"
    response_template: "{success}"
    error_template: "Failed to end party, because {error}"
  - prefix: "hello"
    response_template: "{success}"
    error_template: "Failed to say hello, because {error}"
  - prefix: "mic"
    response_template: "Microphone set to {state}"
    error_template: "Failed to set microphone: {error}"
  - prefix: "pack"
    response_template: "Successfully opened luck pack {item}"
    error_template: "Failed to open luck pack: {error}"
appium:
  host: "192.168.50.103"
  port: 4723

logging:
  directory: "../logs"

device:
  name: "192.168.50.151:5555"
  platform_name: "Android"
  platform_version: "10"
  automation_name: "UiAutomator2"
  no_reset: true 
